version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install --frozen-lockfile

  pre_build:
    commands:
      - npx prisma generate

  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'package.json'
    - 'package-lock.json'
    - 'build/**/*'
discard-paths: yes
