version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript pnpm
      - npm i --save-dev @types/node
      - pnpm install --frozen-lockfile

  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'scripts/**/*'
    - 'appspec.yml'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'build/**/*'
    - 'node_modules/**/*'

discard-paths: yes
