version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript pnpm
      - pnpm install --frozen-lockfile

  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'build/**/*'
discard-paths: yes
