FROM --platform=linux/amd64 node:18-alpine

WORKDIR /app

# Add Python and other build dependencies as a virtual package group
RUN apk add --no-cache --virtual .build-deps python3 make g++

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

RUN npm install -g pnpm  && \
    pnpm install --frozen-lockfile

COPY . .

RUN npx prisma generate 

RUN pnpm run build \
    && apk del .build-deps

# Command to run your application
CMD ["npm", "start"]
