FROM --platform=linux/amd64 node:18-alpine

WORKDIR /app

RUN apk add --no-cache --virtual python

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

ENV NODE_ENV production

RUN npm -g install pnpm

RUN pnpm i --frozen-lockfile

COPY . .

RUN npm run build \
    && apk del .build-deps

CMD npm start